### ISSUE TITLE
Broken URL in /travel/

### ISSUE THREAD

**Issue by gaurav** [USDA-ARS-GBRU/ml-training-site#8]
On the [/travel/](https://usda-ars-gbru.github.io/ml-training-site/travel/), the first link (to the registration page) goes to `https://usda-ars-gbru.github.io/register/` rather than [/register/](https://usda-ars-gbru.github.io/ml-training-site/register/). I tried to fix it in f7d3bd092de3 but without success.

**Comment by arivers** [comment]
Weird, these work when I run Jekyll locally but not on Github. I'll fix it.

**Comment by arivers** [comment]
Fixed ba adding `baseurl` to `_config.yml` and changing links like `/travel/` to `/ml-training-site/travel/`
